apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: prod

data:
  redis.conf: |
    bind 0.0.0.0

    protected-mode yes

    port 6379

    requirepass ${REDIS_PASSWORD}

    appendonly yes
    save ""

    maxmemory 1500mb
    maxmemory-policy allkeys-lru

    tcp-keepalive 60
    timeout 0

    dir /data
