apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: prod

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: redis

          image: redis:8-alpine
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -c
            - |
              sed "s/\${REDIS_PASSWORD}/$REDIS_PASSWORD/g" /etc/redis/redis.conf > /tmp/redis.conf
              exec redis-server /tmp/redis.conf

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD

          ports:
            - containerPort: 6379

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 2Gi

          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis

            - name: redis-data
              mountPath: /data

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli --no-auth-warning -a "$REDIS_PASSWORD" ping

            periodSeconds: 5
            failureThreshold: 30

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli --no-auth-warning -a "$REDIS_PASSWORD" ping

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli --no-auth-warning -a "$REDIS_PASSWORD" ping

            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3

      volumes:
        - name: redis-config
          configMap:
            name: redis-config

        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pvc
