
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - installation.yaml
  - ghcr-pull-sealed.yaml

images:
  - name: quay.io/argoproj/argocd
    newName: ghcr.io/samuelmelo98/mirror/quay.io/argoproj/argocd
    newTag: v3.5.1

  - name: ghcr.io/dexidp/dex
    newName: ghcr.io/samuelmelo98/mirror/ghcr.io/dexidp/dex
    newTag: v2.45.0

  - name: public.ecr.aws/docker/library/redis
    newName: ghcr.io/samuelmelo98/mirror/public.ecr.aws/docker/library/redis
    newTag: 8.2.3-alpine

patches:
  - path: image-pull-secret-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment|StatefulSet

  - path: argocd-cm-patch.yaml
  - path: argocd-cmd-params-patch.yaml
  - path: argocd-rbac-patch.yaml

  # Preserva o Secret interno existente no Kubernetes
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
      $patch: delete
