resources:
  - ../../base

configMapGenerator:
  - name: ingress-config
    literals:
      - HOST=string-api.cluster.stringtecnologiadf.org

replacements:
  - source:
      kind: ConfigMap
      name: ingress-config
      fieldPath: data.HOST
    targets:
      - select:
          kind: Ingress
          name: app
        fieldPaths:
          - spec.rules.0.host
