apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-ia-data
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
