apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base
- documentos-pvc.yaml

namePrefix: string-api-

images:
- name: IMAGE_PLACEHOLDER
  newName: ghcr.io/samuelmelo98/string-api
  newTag: 6.0.6

replicas:
- count: 1
  name: app

labels:
- includeSelectors: true
  pairs:
    app: string-api


  # 🔥 INGRESS

  # 🔥 DEPLOYMENT (Portas + Variáveis)








  # 🔥 DEPLOYMENT (PVC DOCUMENTOS)


  # 🔥 SERVICE (targetPort)

  # 🔥 SERVICE (selector)

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: string-api.cluster.stringtecnologiadf.org
  target:
    kind: Ingress
    name: app
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 8080

    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: SPRING_PROFILES_ACTIVE
          value: prod

        - name: URL
          valueFrom:
            secretKeyRef:
              name: string-api-secret
              key: infosimples-url

        - name: KEY
          valueFrom:
            secretKeyRef:
              name: string-api-secret
              key: infosimples-key

        - name: USUARIO
          valueFrom:
            secretKeyRef:
              name: string-api-secret
              key: db-user

        - name: SENHA
          valueFrom:
            secretKeyRef:
              name: string-api-secret
              key: db-pass
       - name: REDIS_PASSWORD
         valueFrom:
           secretKeyRef:
             name: string-api-secret
             key: redis-password

        - name: NAME_SERVER
          valueFrom:
            secretKeyRef:
              name: string-api-secret
              key: name-server

        - name: PORT
          valueFrom:
            secretKeyRef:
              name: string-api-secret
              key: name-port
  target:
    kind: Deployment
    name: app
- patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value:
        - name: documentos
          persistentVolumeClaim:
            claimName: string-api-documentos-pvc

    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
        - name: documentos
          mountPath: /data/documentos
  target:
    kind: Deployment
    name: app
- patch: |-
    - op: replace
      path: /spec/ports/0/targetPort
      value: 8080
  target:
    kind: Service
    name: app
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: string-api
  target:
    kind: Service
    name: app
