apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: prod
data:
  config.yml: |
    kafka:
      clusters:
        - name: prod-cluster
          bootstrapServers: kafka-cluster-kafka-bootstrap.prod.svc.cluster.local:9092

    auth:
      type: OAUTH2
      oauth2:
        client:
          keycloak:
            clientId: kafka-ui
            clientSecret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid
            issuer-uri: https://auth.stringtecnologiadf.org/realms/stringtecnologia
            user-name-attribute: preferred_username
            client-name: keycloak
            provider: keycloak
            redirect-uri: https://kafka.cluster.stringtecnologiadf.org/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            custom-params:
              type: keycloak
