apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

namePrefix: exemplo-kafka-

images:
  - name: IMAGE_PLACEHOLDER
    newName: ghcr.io/samuelmelo98/exemplo-kafka
    newTag: latest

replicas:
  - name: app
    count: 1

labels:
  - pairs:
      app: exemplo-kafka
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8081
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: kafka-cluster-kafka-bootstrap.prod.svc.cluster.local:9092

  - target:
      kind: Service
      name: app
    patch: |-
      - op: replace
        path: /spec/ports/0/targetPort
        value: 8081
      - op: replace
        path: /spec/selector/app
        value: exemplo-kafka

  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: exemplo-kafka.cluster.stringtecnologiadf.org
