apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: bancos
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
      protocol: TCP
