apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:26.7.2
  startOptimized: false
  db:
    vendor: postgres
    host: keycloak-postgres
    port: 5432
    database: keycloak
    schema: public
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: https://auth.stringtecnologiadf.org
    strict: true
  proxy:
    headers: xforwarded
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
