apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- serviceaccount.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- networkpolicy.yaml
- sealed-secret.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: ghcr.io/samuelmelo98/string-emails
  newTag: 2.0.0
