resources:
  - ../../../base

namePrefix: site-html-

images:
  - name: IMAGE_PLACEHOLDER
    newName: ghcr.io/samuelmelo98/site-html
    newTag: latest

labels:
  - pairs:
      app: site-html
    includeSelectors: true

patches:
  - target:
      kind: Ingress
      name: app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: site-html.cluster.stringtecnologiadf.org
