resources:
- ../../../base

namePrefix: site-html-

images:
- name: IMAGE_PLACEHOLDER
  newName: ghcr.io/samuelmelo98/site-html
  newTag: 4.1.5

replicas:
- count: 2
  name: app

labels:
- includeSelectors: true
  pairs:
    app: site-html


patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: site-html.cluster.stringtecnologiadf.org
  target:
    kind: Ingress
    name: app
- patch: |-
    - op: replace
      path: /spec/selector/app
      value: site-html
  target:
    kind: Service
    name: app
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
