apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:portfolio
  policy.csv: |
    p, role:portfolio, applications, get, */*, allow
    p, role:portfolio, projects, get, *, allow
