apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/samuelmelo98/app-cluster.git
    targetRevision: main
    path: k8s/overlays/prod/infrastructure/keycloak-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: keycloak-postgres
      namespace: keycloak
      jsonPointers:
        - /spec/volumeClaimTemplates/0/status
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
