apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-bancos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/samuelmelo98/app-cluster.git
    targetRevision: main
    path: k8s/overlays/prod/infrastructure/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: bancos
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: postgres
      jsonPointers:
        - /spec
