apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-bancos
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/samuelmelo98/app-cluster.git
    targetRevision: main
    path: k8s/overlays/prod/infrastructure/postgres

  destination:
    server: https://kubernetes.default.svc
    namespace: bancos

  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: postgres
      namespace: bancos
      jsonPointers:
        - /spec/volumeClaimTemplates/0/status

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Force=true
      - Replace=false
